### ISSUE TITLE
watch *v1.StorageClass: unknown issue

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/volume-snapshot-mover#120]
E0718 19:25:11.116331       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Failed to watch *v1.StorageClass: unknown (get storageclasses.storage.k8s.io)

**Comment by shubham-pampattiwar** [comment]
Fix https://github.com/openshift/oadp-operator/pull/766
