### ISSUE TITLE
Things to determine

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/volume-snapshot-mover#91]
1. Run multiple replicationSource and see how volsync handles it? serial or parallel execution
2. Same cluster: Take backup with DM flag enabled, run restore with DM flag disabled

**Comment by eemcmullan** [comment]
1. I ran 3 replicationSources at once, and it seems as if they run in parallel. They completed within a couple seconds of each other:
`  - lastTransitionTime: "2022-06-17T14:38:03Z"
    message: Reconcile complete
    reason: ReconcileComplete
    status: "True"
    type: Reconciled
  lastManualSync: test-trigger
  lastSyncTime: "2022-06-17T14:38:29Z"`
  
`  - lastTransitionTime: "2022-06-17T14:38:04Z"
    message: Reconcile complete
    reason: ReconcileComplete
    status: "True"
    type: Reconciled
  lastManualSync: test-trigger
  lastSyncTime: "2022-06-17T14:38:30Z"`
  
  `  - lastTransitionTime: "2022-06-17T14:38:10Z"
    message: Reconcile complete
    reason: ReconcileComplete
    status: "True"
    type: Reconciled
  lastManualSync: test-trigger
  lastSyncTime: "2022-06-17T14:38:35Z"`

**Comment by eemcmullan** [comment]
2. Expected behavior found while testing this. Backup using data mover was successful. Restore without data mover did restore the VSB, but the custom CSI plugin was not used, so a native restore was completed.

**Comment by eemcmullan** [comment]
Closing as steps are completed.
